### ISSUE TITLE
Firebase Timestamp Conversion

### ISSUE THREAD

**Issue by dannylu03** [CSC207-2022F-UofT/course-project-translate-chat-program#45]
In the DBService, I'm having a bug in trying to convert the Firebase Timestamp datatype to the Java Date datatype.

**Comment by muzammil004** [comment]
You can use the DocumentSnapshot.getDate(String field) method to convert fields of a document to a java.util.Date object.
This is the documentation: https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentSnapshot#getDate(java.lang.String)
So you would make a new DocumentSnapshot that has a reference to a message document in our database, and then call the getDate method with the String parameter "timestamp".

Note: Check line 79 of my MessageSearchFirebaseSytem class if you want an example (it's been merged to the main branch).
