### ISSUE TITLE
Reference to User from Views

### ISSUE THREAD

**Issue by SlothfulAlfred** [CSC207-2022F-UofT/course-project-translate-chat-program#65]
We have a direct reference to `User` from some of the views, namely `HomeScreen` and `LoginScreen`. We can solve this by implementing the observer design pattern.

**Comment by SlothfulAlfred** [comment]
As a follow up to this, I list below the violations of clean architecture of this nature - referencing an entity outside of a use case interactor / implementation of gateway -  that I have found in our codebase:

# References to `User`
- HomeScreen line 21 
- HomeScreen line 31 
- LoginScreen line 88 (Indirect)
- ProfileScreen line 24 
- ProfileScreen line 28 
- CustomizationController lines 27, 40, 53 
- ContactScreen line 72 
- LoginResponse lines 12, 22, 28 
- CustomizationData lines 10, 19, 54

# References to `Message` 
- ChatScreen line 103 
- ChatScreen line 105 
- SendMessageController line 36  
- MessageSearchResponse line 10
- MessageSearchResponse line 18 
- MessageSearchResponse line 45 
- SendMessageResponse line 7
- SendMessageResponse line 11 
- SendMessageResponse line 17 
- SearchBarPanel line 42
- SearchBarPanel line  51 

# Other bad references
- ContactScreen line 24, 72 reference to `DBService` (not an entity but still shouldn't be accessed from view)

**Comment by muzammil004** [comment]
The remaining violations have been addressed in PR #82 .
